### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by Divyansh-Mehta** [Return0-iiitdwd/10-weeks-of-DSA#1]
Include
- General information about 10 weeks program along with poster
- Week wise topics
- Goal of this repository (That is to maintain code base for practice questions, assignments and learning material).

**Comment by SmrutiPatil** [comment]
![10 week program](https://user-images.githubusercontent.com/99034389/198373525-eb0289fd-7ec7-4b0e-96e1-5ec07acbb466.png)

**Comment by Divyansh-Mehta** [comment]
@SmrutiPatil Can you edit this in the readme.md file and then make a pull request. In addition to poster also write something about the 10 weeks program and also include the schedule for the 10weeks (You can ask @Shravyabhat for the schedule)
Here is a link for reference (How to edit readme.md file)
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
